authentication/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include

from authentication.views import SignupView, LoginView
from django.contrib.auth import views

urlpatterns = [
    path('signup', SignupView.as_view(), name="signup"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('password_change', PasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset', PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logic.urls')),
    path('auth/', include('authentication.urls')),
]

authentication/models.py
from getpass import getpass

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models

# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self, email, password, lastname, firstname, **extrafields):
        if not email:
            ValueError("Email field is required")
        if not firstname:
            ValueError("Firstname field is required")
        if not lastname:
            ValueError("Lastname field is required")

        user = self.model(
            email=self.normalize_email(email),
            password=password,
            firstname=firstname,
            lastname=lastname,
            **extrafields
        )

        user.is_active = True
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_superuser(self, email, password, lastname, firstname, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        user = self.create_user(email, password, lastname, firstname, **extra_fields)
        user.is_admin = True
        # used by the PermissionsMixin to
        # grant all permissions
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=50,
        unique=True,
        error_messages={"unique": "A user with this email already exists"},
    )
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()
    REQUIRED_FIELDS = ["firstname", "lastname", "password"]
    USERNAME_FIELD = "email"

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_username(self):
        return self.email

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.firstname, self.lastname)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.firstname

        # allows assignment property to the image value
        # from the view

    def __setitem__(self, key, value):
        self.profile_picture = value

    @property
    def is_staff(self):
        return self.is_superuser

authentication/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

from authentication.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    firstname = forms.CharField(max_length=100, required=True)
    lastname = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ("firstname", "lastname", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        label="Email address",
        max_length=254,
        widget=forms.EmailInput(attrs={'autofocus': True}),
    )

    #
    # def clean(self):
    #     email = self.cleaned_data.get('email')
    #     password = self.cleaned_data.get('password')
    #
    #     if email is not None and password:
    #         self.user_cache = authenticate(self.request, email=email, password=password)
    #         if self.user_cache is None:
    #             raise forms.ValidationError(
    #                 self.error_messages['invalid_login'],
    #                 code='invalid_login',
    #                 params={'username': self.username_field.verbose_name},
    #             )
    #         else:
    #             self.confirm_login_allowed(self.user_cache)
    #
    #     return self.cleaned_data

authentication/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView

from authentication.forms import SignupForm, LoginForm
from authentication.models import User
from django.contrib.auth import views


class SignupView(SuccessMessageMixin, CreateView):
    model = User
    template_name = "authentication/register.html"
    form_class = SignupForm
    success_url = reverse_lazy("login")
    success_message = 'Registration was successful'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect("index")
        return super(SignupView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        # runs if the form is valid

        return super().form_valid(form)

    def form_invalid(self, form):
        # import pdb; pdb.set_trace()
        for k, err in form.errors.items():
            messages.error(self.request, err[0])
        return super().form_invalid(form)


class LoginView(SuccessMessageMixin, views.LoginView):
    template_name = "authentication/login.html"
    success_url = reverse_lazy("index")
    form_class = LoginForm

    def form_invalid(self, form):
        for k, err in form.errors.items():
            messages.error(self.request, err[0])

        return super().form_invalid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect("index")
        return super(LoginView, self).get(request, *args, **kwargs)

templates/authentication/login.html
{% load static %}
{% load custom_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href={% static 'css/bootstrap.min.css' %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static 'css/style.css' %} rel="stylesheet">
</head>

<body class="text-center">
<div class="container my-5 justify-content-center align d-flex">
    <div class="col-5">

        {% include "partials/messages.html" %}

        <form class="form-signin" method="POST" action={% url "login" %}>
            {% csrf_token %}
            <div class="text-center mb-4">
                <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
                     width="72" height="72">
                <h1 class="h3 mb-3 font-weight-normal">Login labels</h1>
            </div>

            <div class="form-label-group">
                {{ form.username|addcss:"form-control" }}
                <label for="id_email">Email address</label>
            </div>

            <div class="form-label-group">
                {{ form.password|addcss:"form-control" }}
                <label for="id_password1">Password</label>
            </div>


            <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2018</p>
        </form>
        <p> New user?<a href={% url "signup" %}>Sign up</a> or Go <a href={% url "index" %}>Home</a></p>

    </div>
</div>
</body>
</html>

templates/authentication/register.html
{% load static %}
{% load custom_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href={% static 'css/bootstrap.min.css' %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static 'css/style.css' %} rel="stylesheet">
</head>

<body class="text-center">
<div class="container my-5 justify-content-center align d-flex">
    <div class="col-5">

        {% include "partials/messages.html" %}

        <form class="form-signin" method="POST" action={% url "signup" %}>
            {% csrf_token %}
            <div class="text-center mb-4">
                <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
                     width="72" height="72">
                <h1 class="h3 mb-3 font-weight-normal">Sign up labels</h1>
            </div>

            <div class="form-row justify-content-between">
                <div class="form-label-group">
                    {{ form.firstname|addcss:"form-control" }}
                    <label for="id_firstname">Firstname</label>
                </div>
                <div class="form-label-group">
                    {{ form.lastname|addcss:"form-control" }}
                    <label for="id_lastname">Lastname</label>
                </div>
            </div>


            <div class="form-label-group">
                {{ form.email|addcss:"form-control" }}
                <label for="id_email">Email address</label>
            </div>

            <div class="form-label-group">
                {{ form.password1|addcss:"form-control" }}
                <label for="id_password1">Password</label>
            </div>
            <div class="form-label-group">
                {{ form.password2|addcss:"form-control" }}
                <label for="id_password2">Confirm password</label>
            </div>


            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2018</p>
        </form>
       <p> Already have an account? <a href={% url "login" %}>Login In</a> or Go <a href={% url "index" %}>Home</a></p>


    </div>
</div>
</body>
</html>